# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fialloui.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Fiallo(object):
    def setupUi(self, Fiallo):
        Fiallo.setObjectName("Fiallo")
        Fiallo.resize(640, 475)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Fiallo)
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.listServices = QtWidgets.QListWidget(Fiallo)
        self.listServices.setProperty("showDropIndicator", True)
        self.listServices.setAlternatingRowColors(True)
        self.listServices.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.listServices.setFlow(QtWidgets.QListView.TopToBottom)
        self.listServices.setBatchSize(100)
        self.listServices.setObjectName("listServices")
        self.verticalLayout_2.addWidget(self.listServices)
        self.verticalLayout_2.setStretch(0, 5)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.tabWidget = QtWidgets.QTabWidget(Fiallo)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.progressUpdate = QtWidgets.QProgressBar(self.tab)
        self.progressUpdate.setEnabled(False)
        self.progressUpdate.setProperty("value", 0)
        self.progressUpdate.setObjectName("progressUpdate")
        self.gridLayout_2.addWidget(self.progressUpdate, 5, 1, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineUpdateFile = QtWidgets.QLineEdit(self.tab)
        self.lineUpdateFile.setEnabled(False)
        self.lineUpdateFile.setObjectName("lineUpdateFile")
        self.gridLayout_3.addWidget(self.lineUpdateFile, 0, 0, 1, 2)
        self.pushBrowse = QtWidgets.QPushButton(self.tab)
        self.pushBrowse.setObjectName("pushBrowse")
        self.gridLayout_3.addWidget(self.pushBrowse, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setLineWidth(0)
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 2, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_3, 3, 0, 1, 2)
        self.pushUpdate = QtWidgets.QPushButton(self.tab)
        self.pushUpdate.setEnabled(False)
        self.pushUpdate.setObjectName("pushUpdate")
        self.gridLayout_2.addWidget(self.pushUpdate, 5, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.listCommands = QtWidgets.QListWidget(self.tab_2)
        self.listCommands.setObjectName("listCommands")
        self.verticalLayout_3.addWidget(self.listCommands)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineCommand = QtWidgets.QLineEdit(self.tab_2)
        self.lineCommand.setObjectName("lineCommand")
        self.horizontalLayout.addWidget(self.lineCommand)
        self.pushAddCommand = QtWidgets.QPushButton(self.tab_2)
        self.pushAddCommand.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("list-add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushAddCommand.setIcon(icon)
        self.pushAddCommand.setIconSize(QtCore.QSize(22, 22))
        self.pushAddCommand.setObjectName("pushAddCommand")
        self.horizontalLayout.addWidget(self.pushAddCommand)
        self.pushDelCommand = QtWidgets.QPushButton(self.tab_2)
        self.pushDelCommand.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("list-remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushDelCommand.setIcon(icon1)
        self.pushDelCommand.setIconSize(QtCore.QSize(22, 22))
        self.pushDelCommand.setObjectName("pushDelCommand")
        self.horizontalLayout.addWidget(self.pushDelCommand)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.listParameter = QtWidgets.QListWidget(self.tab_2)
        self.listParameter.setObjectName("listParameter")
        item = QtWidgets.QListWidgetItem()
        self.listParameter.addItem(item)
        self.verticalLayout_3.addWidget(self.listParameter)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineParameter = QtWidgets.QLineEdit(self.tab_2)
        self.lineParameter.setObjectName("lineParameter")
        self.horizontalLayout_3.addWidget(self.lineParameter)
        self.pushAddParameter = QtWidgets.QPushButton(self.tab_2)
        self.pushAddParameter.setText("")
        self.pushAddParameter.setIcon(icon)
        self.pushAddParameter.setIconSize(QtCore.QSize(22, 22))
        self.pushAddParameter.setObjectName("pushAddParameter")
        self.horizontalLayout_3.addWidget(self.pushAddParameter)
        self.pushDelParameter = QtWidgets.QPushButton(self.tab_2)
        self.pushDelParameter.setText("")
        self.pushDelParameter.setIcon(icon1)
        self.pushDelParameter.setIconSize(QtCore.QSize(22, 22))
        self.pushDelParameter.setObjectName("pushDelParameter")
        self.horizontalLayout_3.addWidget(self.pushDelParameter)
        self.pushExecute = QtWidgets.QPushButton(self.tab_2)
        self.pushExecute.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("run-build.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushExecute.setIcon(icon2)
        self.pushExecute.setIconSize(QtCore.QSize(22, 22))
        self.pushExecute.setObjectName("pushExecute")
        self.horizontalLayout_3.addWidget(self.pushExecute)
        self.horizontalLayout_3.setStretch(0, 15)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.labelCommand = QtWidgets.QLabel(self.tab_2)
        self.labelCommand.setText("")
        self.labelCommand.setObjectName("labelCommand")
        self.verticalLayout_3.addWidget(self.labelCommand)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.horizontalLayout_2.addWidget(self.tabWidget)
        self.horizontalLayout_2.setStretch(0, 5)
        self.horizontalLayout_2.setStretch(1, 10)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.textLog = QtWidgets.QTextBrowser(Fiallo)
        self.textLog.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textLog.setObjectName("textLog")
        self.verticalLayout_4.addWidget(self.textLog)
        self.verticalLayout_4.setStretch(0, 85)
        self.verticalLayout_4.setStretch(1, 15)

        self.retranslateUi(Fiallo)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Fiallo)

    def retranslateUi(self, Fiallo):
        _translate = QtCore.QCoreApplication.translate
        Fiallo.setWindowTitle(_translate("Fiallo", "Fiallo"))
        self.pushBrowse.setText(_translate("Fiallo", "Browse"))
        self.pushUpdate.setText(_translate("Fiallo", "Update"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Fiallo", "Update"))
        __sortingEnabled = self.listParameter.isSortingEnabled()
        self.listParameter.setSortingEnabled(False)
        item = self.listParameter.item(0)
        item.setText(_translate("Fiallo", "null"))
        self.listParameter.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Fiallo", "Command"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Fiallo", "Skripting"))

